object Versions {
    const val KotlinVersion = "1.6.10"
    const val CoroutinesVersion = "1.6.0-RC3"
    const val SerializationJson = "1.3.1"
    const val BuildToolsVersion = "31.0.0"
    const val AndroidGradlePluginVersion = "7.0.4"
    const val AndroidGradlePluginApiVersion = "7.0.4"
    const val DaggerVersion = "2.40.5"
    const val GoogleServices = "4.3.10"
    const val Crashlytics = "2.8.1"

    const val MaterialVersion = "1.5.0-rc01"
    const val AppCompat = "1.4.0"
    const val ComposeVersion = "1.1.0-rc01"
    const val ComposeCompilerVersion = "1.1.0-rc02"
    const val AndroidXCoreVersion = "1.7.0"
    const val TimberVersion = "4.7.1"
    const val ActivityComposeVersion = "1.4.0"
    const val ComposeNavigation = "2.4.0-rc01"
    const val CoreSplashScreenVersion = "1.0.0-alpha02"
    const val DetektVersion = "1.18.1"
    const val KtlintVersion = "10.1.0"
    const val CoreLibraryDesugaringVersion = "1.1.5"
    const val Accompanist = "0.21.5-rc"
    const val DrawablePainter = "0.15.0"
    const val Arrow = "1.0.1"
    const val Retrofit = "2.9.0"
    const val OkHttp = "4.9.3"

    const val AndroidJUnit4 = "1.1.3"
    const val Espresso = "3.4.0"
    const val JUnit4 = "4.13"
}
